---
- name: checkout anyenv_repo for system
  git: repo="{{ git_repo }}" dest="{{ install_dir }}"

- name: add anyenv initialization to profile system-wide
  template: src=anyenv.sh.j2 dest=/etc/profile.d/anyenv.sh owner=root group=root mode=0755
  become: yes
  when:
    - ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin'
