---
- name: create default user-dirs
  file: >
    path="/etc/skel/{{ item }}"
    state=directory
  with_items:
    - Desktop
    - Downloads
    - Templates
    - Public
    - Documents
    - Music
    - Pictures
    - Videos

- name: xdg setting
  copy: >
    dest="/etc/xdg/user-dirs.conf"
    src="user-dirs.conf"
- name: create user
  user: >
    name="{{ users_username }}"
    groups="{{ users_groups }}"
    shell="/bin/bash"
    password="{{ users_password | password_hash('sha512') }}"
    update_password=on_create
- name: add to sudoers
  lineinfile: >
    dest="/etc/sudoers.d/{{ users_username }}"
    line="{{ users_username }} ALL=(ALL:ALL) NOPASSWD:ALL"
    create=yes
- stat:
    path: /home/{{ users_username }}/.anyenv
  register: anyenv_is_installed
- name: install anyenv
  shell: git clone https://github.com/riywo/anyenv /home/{{ users_username }}/.anyenv
  when: anyenv_is_installed.stat.exists == false
- name: update anyenv
  shell: cd /home/{{ users_username }}/.anyenv && git fetch && git rebase origin master
  register: git_messages
  changed_when: git_messages.stdout != "Current branch master is up to date."
- name: chown anyenv
  file: path=/home/{{ users_username }}/.anyenv owner={{ users_username}} group={{ users_group }} mode=0766 state=directory recurse=yes
- name: add bashrc
  lineinfile: dest=/home/{{ users_username }}/.bashrc line="export PATH=/home/{{ users_username }}/.anyenv/bin:$PATH"
