---
- name: install xserver
  apt: 
    name: 
    - xserver-xorg
    - xserver-xorg-core
    - xfonts-base
    - xinit
    - x11-xserver-utils
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop

- name: install fonts
  apt: 
    name: 
    - fonts-ipa*
    - fonts-noto
    - fonts-ricty-diminished
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop

- name: install xfce
  apt: 
    name: 
    - xfwm4
    - xfce4-panel
    - xfce4-settings
    - xfce4-session
    - xfce4-terminal
    - xfdesktop4
    - xfce4-taskmanager
    - lightdm
    - lightdm-gtk-greeter
    - thunar
    - gvfs
    - gvfs-backends
    - policykit-1
    - udisks2
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - pulseaudio
    - gstreamer1.0-pulseaudio
    - firefox
    - firefox-locale-en
    - firefox-locale-ja
    - plymouth-x11
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop

- name: install virtualbox utils
  apt: 
    name: 
    - dkms
    - virtualbox-guest-dkms
    - virtualbox-guest-x11
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop
  notify:
    - reboot server

- name: greeter setting
  lineinfile: >
    dest="/usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf"
    line="{{ item }}"
  with_items:
    - "allow-guest=false"
    - "greeter-hide-users=true"
    - "greeter-show-manual-login=true"

- name: keyboard setting
  lineinfile: >
    dest="/etc/default/keyboard"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: "XKBMODEL=", line: 'XKBMODEL="{{ keyboardmodel }}"' }
    - { regexp: "XKBLAYOUT=", line: 'XKBLAYOUT="{{ keyboardlayout }}"' }
    - { regexp: "XKBVARIANT=", line: 'XKBVARIANT=""' }

- name: grub setting
  lineinfile: >
    dest="/etc/default/grub.d/50-cloudimg-settings.cfg"
    regexp="GRUB_CMDLINE_LINUX_DEFAULT.*"
    line='GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  register: grub_config

- name: update grub
  command: update-grub
  when: grub_config is changed

- name: update initramfs
  command: update-initramfs -u -k all
  when: grub_config is changed

- name: reboot server
  reboot:
  async: 1
  poll: 0
  ignore_errors: true
  when: install_desktop is changed or grub_config is changed

- name: wait for reboot
  wait_for_connection:
    delay: 30
    timeout: 300
  when: install_desktop is changed or grub_config is changed
